#!/usr/bin/env node
import {Builtins, Cli} from 'clipanion';
import {DoctorCommand} from './commands/doctor.js';
import {RunCommand} from './commands/run.js';
import {StatusCommand} from './commands/status.js';
import {ResumeCommand} from './commands/resume.js';
import {CancelCommand} from './commands/cancel.js';
import {AttachCommand} from './commands/attach.js';
import {MachineCommand} from './commands/machine.js';
import {MCPCommand} from './commands/mcp.js';
import {DashboardCommand} from './commands/dashboard.js';
import {SetupProductCommand} from './commands/setup-product.js';
import {DemoCommand} from './commands/demo.js';
import {ExamplesListCommand, ExamplesShowCommand} from './commands/examples.js';
import {MemoryCreateCommand, MemoryDeleteCommand, MemoryGetCommand, MemoryListCommand, MemorySupersedeCommand} from './commands/memory.js';
import {TeamCancelCommand, TeamCancelTurnCommand, TeamCloseCommand, TeamFollowUpCommand, TeamListCommand, TeamShowCommand, TeamStartCommand} from './commands/team.js';
import {TeamHandoffBindCommand, TeamHandoffCreateCommand, TeamHandoffListCommand, TeamHandoffShowCommand} from './commands/team-handoff.js';
import {DriversInspectCommand, RoutingDisableCommand, RoutingEnableCommand, RoutingRefreshCommand, RoutingShowCommand} from './commands/routing.js';

const cli = new Cli({binaryLabel: 'Fishyume', binaryName: 'fishyume', binaryVersion: '0.2.1-alpha.1'});
cli.register(Builtins.HelpCommand);
cli.register(Builtins.VersionCommand);
cli.register(DashboardCommand);
cli.register(DemoCommand);
cli.register(ExamplesListCommand);
cli.register(ExamplesShowCommand);
cli.register(SetupProductCommand);
cli.register(DoctorCommand);
cli.register(RunCommand);
cli.register(StatusCommand);
cli.register(ResumeCommand);
cli.register(CancelCommand);
cli.register(AttachCommand);
cli.register(MachineCommand);
cli.register(MCPCommand);
cli.register(MemoryCreateCommand);
cli.register(MemoryGetCommand);
cli.register(MemoryListCommand);
cli.register(MemorySupersedeCommand);
cli.register(MemoryDeleteCommand);
cli.register(TeamStartCommand);
cli.register(TeamListCommand);
cli.register(TeamShowCommand);
cli.register(TeamCancelCommand);
cli.register(TeamFollowUpCommand);
cli.register(TeamCancelTurnCommand);
cli.register(TeamCloseCommand);
cli.register(TeamHandoffCreateCommand);
cli.register(TeamHandoffListCommand);
cli.register(TeamHandoffShowCommand);
cli.register(TeamHandoffBindCommand);
cli.register(DriversInspectCommand);
cli.register(RoutingShowCommand);
cli.register(RoutingEnableCommand);
cli.register(RoutingDisableCommand);
cli.register(RoutingRefreshCommand);
const args = process.argv.slice(2);
// Keep the historical `setup codex` spelling as a compatibility alias for the
// single product setup command without registering an ambiguous Clipanion path.
if (args[0] === 'setup' && args[1] === 'codex') args.splice(1, 1);
await cli.runExit(args.length === 0 ? ['dashboard'] : args, Cli.defaultContext);
